name: CI/CD Node.js - Générateur de citations

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Tests unitaires
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test

  build:
    name: Build du projet
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - run: echo "Build du projet réussi !"

  deploy:
    name: Déploiement sur GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      
      # Étape pour générer le fichier index.html
      - name: Générer le fichier index.html
        run: |    
          echo 'async function chargerCitation() {' > src/public/script.js
          echo '  const citationElement = document.getElementById("citation");' >> src/public/script.js
          echo '  try {' >> src/public/script.js
          echo '    const response = await fetch("https://zenquotes.io/api/random");' >> src/public/script.js
          echo '    const data = await response.json();' >> src/public/script.js
          echo '    citationElement.innerText = `${data[0].q} — ${data[0].a}`;' >> src/public/script.js
          echo '  } catch (error) {' >> src/public/script.js
          echo '    citationElement.innerText = "Impossible de charger la citation.";' >> src/public/script.js
          echo '  }' >> src/public/script.js
          echo '}' >> src/public/script.js
          echo 'document.getElementById("nouvelle").addEventListener("click", chargerCitation);' >> src/public/script.js
          echo 'window.addEventListener("load", chargerCitation);' >> src/public/script.js
      # Étape de déploiement
      - name: Déploiement sur GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/public
