name: CI/CD Node.js - Générateur de citations

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Tests unitaires
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test

  build:
    name: Build du projet
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - run: echo "Build du projet réussi !"

  deploy:
    name: Déploiement sur GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      
      # Étape pour générer le fichier index.html
      - name: Générer le fichier index.html
        run: |
            cat > index.html << 'EOF'
            <!DOCTYPE html>
            <html lang="fr">
             <head>
            <meta charset="UTF-8">
            <title>Générateur de citations</title>
            <style>
            body { font-family: Arial, sans-serif; padding: 20px; }
            button { margin-top: 10px; padding: 5px 10px; }
            </style>
            </head>
            <body>
            <h1 id="citation">Votre citation apparaîtra ici</h1>
             <script>
            const citations = [
            "Le succès vient à ceux qui persévèrent.",
            "La vie est un mystère à vivre, non un problème à résoudre.",
            "Rien n'est impossible à celui qui croit.",
            "Chaque jour est une nouvelle chance de réussir."
            ];
            function citationAleatoire() {
            const index = Math.floor(Math.random() * citations.length);
            return citations[index];
            }
            const citationElement = document.getElementById("citation");
            citationElement.innerText = citationAleatoire();
            </script>
            </body>
            </html>
          
      # Étape de déploiement
      - name: Déploiement sur GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/public
